name: stage-2-lint-eslint
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stage-2-lint-eslint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/lint
