name: stage-2-dotnet-build
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stage-2-dotnet-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dotnet-build
