name: stage-5-test-vitest
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stage-5-test-vitest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
