name: stage-6-contract
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stage-6-contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/contract
      - uses: ./.github/actions/schema-contract
