name: stage-1-format
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stage-1-format:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/format
