name: stage-7-integration
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stage-7-integration:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/integration
