name: stage-4-dotnet-architecture
on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  stage-4-dotnet-architecture:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dotnet-architecture
